== JWTOptions

++++
 Options related to creation of new tokens.

 If any expiresInMinutes, audience, subject, issuer are not provided, there is no default.
 The jwt generated won't include those properties in the payload.

 Generated jwts will include an iat claim by default unless noTimestamp is specified.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description

|[[algorithm]]`algorithm`
|`String`
|+++
The algorithm to use, it should be one of the alias [HS256, HS384, HS512, RS256, RS384, RS512, ES256, ES384, ES512]+++

|[[expiresInMinutes]]`expiresInMinutes`
|`Number`
|+++
The expiration time for the token in minutes+++

|[[expiresInSeconds]]`expiresInSeconds`
|`Number`
|+++
The expiration time for the token in seconds+++

|[[audience]]`audience`
|`Array of String`
|+++
The target audience of this token+++

|[[audiences]]`audiences`
|`Array of String`
|+++
The target audience of this token+++

|[[subject]]`subject`
|`String`
|+++
The subject of this token+++

|[[issuer]]`issuer`
|`String`
|+++
The issuer of this token+++

|[[noTimestamp]]`noTimestamp`
|`Boolean`
|+++
Disable the generation of issued at claim+++

|[[roles]]`roles`
|`Array of String`
|+++
Add a role to this token.+++

|[[permissions]]`permissions`
|`Array of String`
|+++
Add a permission to this token.+++
|===
