= Vert.x Auth - Authentication and Authorisation

This Vert.x component provides interfaces for authentication and authorisation that can be used from your Vert.x
applications and can be backed by different providers.

It also provides an implementation that uses http://shiro.apache.org/[Apache Shiro] out-of-the-box but you can provide
your own implementation by implementing the `link:groovydoc/io/vertx/groovy/ext/auth/AuthProvider.html[AuthProvider]` interface.

The Vert.x Apache Shiro implementation
currently allows user/role/permission information to be accessed from simple properties files or LDAP servers.

Vert.x auth is also used by vertx-web to handle its authentication and authorisation.

== Basic concepts

_Authentication_ (aka _log in_) means verifying the identity of a user.

_Authorisation_ means verifying a user is allowed to access some resource.

The service uses a familiar user/role/permission model that you will probably know already:

Users can have zero or more roles, e.g. "manager", "developer".

Roles can have zero or more permissions, e.g. a manager might have permission "approve expenses", "conduct_reviews",
and a developer might have a permission "commit_code".

== Authentication

To authenticate a user you use `link:groovydoc/io/vertx/groovy/ext/auth/AuthProvider.html#authenticate(io.vertx.core.json.JsonObject,%20io.vertx.core.Handler)[authenticate]`.

The first argument is a JSON object which contains authentication information. What this actually contains depends
on the specific implementation; for a simple username/password based authentication it might contain something like:

----
{
  "username": "tim"
  "password": "mypassword"
}
----

For an implementation based on JWT token or OAuth bearer tokens it might contain the token information.

Authentication occurs asynchronously and the result is passed to the user on the result handler that was provided in
the call. The async result contains an instance of `link:groovydoc/io/vertx/groovy/ext/auth/User.html[User]` which represents the authenticated
user and contains operations which allow the user to be authorised.

Here's an example of authenticating a user using a simple username/password implementation:

[source,java]
----

def authInfo = [
  username:"tim",
  password:"mypassword"
]

authProvider.authenticate(authInfo, { res ->
  if (res.succeeded()) {

    def user = res.result()

    println("User ${user.principal()} is now authenticated")

  } else {
    res.cause().printStackTrace()
  }
})

----

== Authorisation

Once you have an `link:groovydoc/io/vertx/groovy/ext/auth/User.html[User]` instance you can call methods on it to authorise it.

To check if a user has a specific role you use `link:groovydoc/io/vertx/groovy/ext/auth/User.html#hasRole(java.lang.String,%20io.vertx.core.Handler)[hasRole]`,
to check if a user has all the specified roles you use `link:groovydoc/io/vertx/groovy/ext/auth/User.html#hasRoles(java.util.Set,%20io.vertx.core.Handler)[hasRoles]`,
to check if a user has a specific permission you use `link:groovydoc/io/vertx/groovy/ext/auth/User.html#hasPermission(java.lang.String,%20io.vertx.core.Handler)[hasPermission]`,
to check if a user has all the specified permissions you use `link:groovydoc/io/vertx/groovy/ext/auth/User.html#hasPermissions(java.util.Set,%20io.vertx.core.Handler)[hasPermissions]`.

The results of all the above are provided asynchronously in the handler.

Here's an example of authorising a user:

[source,java]
----

user.hasPermission("admin", { res ->
  if (res.succeeded()) {

    def hasPermission = res.result()

    if (hasPermission) {
      println("User has the permision")
    } else {
      println("User does not have the permision")
    }

  } else {
    res.cause().printStackTrace()
  }
})

----

=== Caching roles and permissions

The user object will cache any roles and permissions so subsequently calls to check if it has the same roles or
permissions will result in the underlying provider being called.

In order to clear the internal cache you can use `link:groovydoc/io/vertx/groovy/ext/auth/User.html#clearCache()[clearCache]`.

=== The User Principal

You can get the Principal corresponding to the authenticated user with `link:groovydoc/io/vertx/groovy/ext/auth/User.html#principal()[principal]`.

What this returns depends on the underlying implementation.

=== Clusterable users

Sometimes users might be put into sessions and clustered to other nodes. For implementations that do not want to
be clustered in this way, they should return `false` from this method.

== The Apache Shiro Auth provider implementation

This component contains an out of the box implementation that uses http://shiro.apache.org/[Apache Shiro].

We provide out of the box support for properties and LDAP based auth using Shiro.

To create an instance of the provider you use `link:groovydoc/io/vertx/groovy/ext/auth/shiro/ShiroAuth.html[ShiroAuth]`. You specify the type of
Shiro auth provider that you want with `ShiroAuthRealmType`, and you specify the
configuration in a JSON object.

Here's an example of creating a Shiro auth provider:

[source,java]
----
import io.vertx.groovy.ext.auth.shiro.ShiroAuth
import io.vertx.ext.auth.shiro.ShiroAuthRealmType

def config = [
  properties_path:"classpath:test-auth.properties"
]

def provider = ShiroAuth.create(vertx, ShiroAuthRealmType.PROPERTIES, config)


----

=== The Shiro properties auth provider

This auth provider implementation uses Apache Shiro to get user/role/permission information from a properties file.

The implementation will, by default, look for a file called `vertx-users.properties` on the classpath.

If you want to change this, you can use the `properties_path` configuration element to define how the properties
file is found.

The default value is `classpath:vertx-users.properties`.

If the value is prefixed with `classpath:` then the classpath will be searched for a properties file of that name.

If the value is prefixed with `file:` then it specifies a file on the file system.

If the value is prefixed with `url:` then it specifies a URL from where to load the properties.

The properties file should have the following structure:

Each line should either contain the username, password and roles for a user or the permissions in a role.

For a user line it should be of the form:

 user.{username}={password},{roleName1},{roleName2},...,{roleNameN}

For a role line it should be of the form:

 role.{roleName}={permissionName1},{permissionName2},...,{permissionNameN}

Here's an example:
----
user.tim = mypassword,administrator,developer
user.bob = hispassword,developer
user.joe = anotherpassword,manager
role.administrator=*
role.manager=play_golf,say_buzzwords
role.developer=do_actual_work
----

When describing roles a wildcard `*` can be used to indicate that the role has all permissions

=== The Shiro LDAP auth provider

The LDAP auth realm gets user/role/permission information from an LDAP server.

The following configuration properties are used to configure the LDAP realm:

`ldap-user-dn-template`:: this is used to determine the actual lookup to use when looking up a user with a particular
id. An example is `uid={0},ou=users,dc=foo,dc=com` - the element `{0}` is substituted with the user id to create the
actual lookup. This setting is mandatory.
`ldap_url`:: the url to the LDAP server. The url must start with `ldap://` and a port must be specified.
An example is `ldap:://myldapserver.mycompany.com:10389`
`ldap-authentication-mechanism`:: TODO
`ldap-context-factory-class-name`:: TODO
`ldap-pooling-enabled`:: TODO
`ldap-referral`:: TODO
`ldap-system-username`:: TODO
`ldap-system-password`:: TODO

=== Using another Shiro Realm

It's also possible to create an auth provider instance using a pre-created Apache Shiro Realm object.

This is done as follows:

[source,java]
----
import io.vertx.groovy.ext.auth.shiro.ShiroAuth

def provider = ShiroAuth.create(vertx, realm)


----

The implementation currently assumes that user/password based authentication is used.

== The JWT auth provider

This component contains an out of the box a JWT implementation.

JSON Web Token is a simple way to send information in the clear (usually in a URL) whose contents can be verified to
be trusted. JWT are well suited for scenarios as:

* In a Single Sign-On scenario where you want a separate authentication server that can then send user information in
  a trusted way.
* Stateless API servers, very well suited for sinple page applications.
* etc...

Before deciding on using JWT, it's important to note that JWT does not encrypt the payload, it only signs it. You
should not send any secret information using JWT, rather you should send information that is not secret but needs to
be verified. For instance, sending a signed user id to indicate the user that should be logged in would work great!
Sending a user's password would be very, very bad.

Its main advantages are:

* It allows you to verify token authenticity.
* It has a json body to contain any variable amount of data you want.
* It's completely stateless.

To create an instance of the provider you use `link:groovydoc/io/vertx/groovy/ext/auth/jwt/JWTAuth.html[JWTAuth]`. You specify the configuration
in a JSON object.

Here's an example of creating a JWT auth provider:

[source,java]
----
import io.vertx.groovy.ext.auth.jwt.JWTAuth

def config = [
  keyStoreURI:"classpath:///keystore.jceks",
  keyStoreType:"jceks",
  keyStorePassword:"secret"
]

def provider = JWTAuth.create(config)

----

A typical flow of JWT usage is that in your application you have one end point that issues tokens, this end point
should be running in SSL mode, there after you verify the request user, say by its username and password you would
do:

[source,java]
----
import io.vertx.groovy.ext.auth.jwt.JWTAuth

def config = [
  keyStoreURI:"classpath:///keystore.jceks",
  keyStoreType:"jceks",
  keyStorePassword:"secret"
]

def provider = JWTAuth.create(config)

// on the verify endpoint once you verify the identity of the user by its username/password
if ("paulo" == username && "super_secret" == password) {
  def token = provider.generateToken([
    sub:"paulo"
  ], [:])
  // now for any request to protected resources you should pass this string in the HTTP header Authorization as:
  // Authorization: Bearer <token>
}

----

=== The JWT keystore file

This auth provider requires a keystore in the classpath or in the filesystem with either a `Mac`
or a `Signature` in order to sign and verify the generated tokens.

The implementation will, by default, look for the following aliases, however not all are required to be present. As
a good practice `HS256` should be present:
----
`HS256`:: HMAC using SHA-256 hash algorithm
`HS384`:: HMAC using SHA-384 hash algorithm
`HS512`:: HMAC using SHA-512 hash algorithm
`RS256`:: RSASSA using SHA-256 hash algorithm
`RS384`:: RSASSA using SHA-384 hash algorithm
`RS512`:: RSASSA using SHA-512 hash algorithm
`ES256`:: ECDSA using P-256 curve and SHA-256 hash algorithm
`ES384`:: ECDSA using P-384 curve and SHA-384 hash algorithm
`ES512`:: ECDSA using P-521 curve and SHA-512 hash algorithm
----

When no keystore is provided the implementation falls back in unsecure mode and signatures will not be verified, this
is useful for the cases where the payload if signed and or encrypted by external means.

== Creating your own auth implementation

If you wish to create your own auth provider you should implement the `link:groovydoc/io/vertx/groovy/ext/auth/AuthProvider.html[AuthProvider]` interface.

We provide an abstract implementation of user called `AbstractUser` which you can subclass
to make your user implementation. This contains the caching logic so you don't have to implement that yourself.

If you wish your user objects to be clusterable you should make sure they implement `ClusterSerializable`.

== JDBC Auth Provider implementation

We provide an implementation of `link:groovydoc/io/vertx/groovy/ext/auth/AuthProvider.html[AuthProvider]` which uses the Vert.x `link:../../vertx-jdbc-client/groovy/groovydoc/io/vertx/groovy/ext/jdbc/JDBCClient.html[JDBCClient]`
to perform authentication and authorisation against any JDBC compliant database.

To create an instance you first need an instance of `link:../../vertx-jdbc-client/groovy/groovydoc/io/vertx/groovy/ext/jdbc/JDBCClient.html[JDBCClient]`. To learn how to create one
of those please consult the documentation for the JDBC client.

Once you've got one of those you can create a `link:groovydoc/io/vertx/groovy/ext/auth/jdbc/JDBCAuth.html[JDBCAuth]` instance as follows:

[source,java]
----
import io.vertx.groovy.ext.jdbc.JDBCClient
import io.vertx.groovy.ext.auth.jdbc.JDBCAuth

def jdbcClient = JDBCClient.createShared(vertx, jdbcClientConfig)

def authProvider = JDBCAuth.create(jdbcClient)

----

Once you've got your instance you can authenticate and authorise with it just like any `link:groovydoc/io/vertx/groovy/ext/auth/AuthProvider.html[AuthProvider]`.

The out of the box config assumes certain queries for authentication and authorisation, these can easily be changed
with the operations `link:groovydoc/io/vertx/groovy/ext/auth/jdbc/JDBCAuth.html#setAuthenticationQuery(java.lang.String)[setAuthenticationQuery]`,
`link:groovydoc/io/vertx/groovy/ext/auth/jdbc/JDBCAuth.html#setPermissionsQuery(java.lang.String)[setPermissionsQuery]` and
`link:groovydoc/io/vertx/groovy/ext/auth/jdbc/JDBCAuth.html#setRolesQuery(java.lang.String)[setRolesQuery]`, if you want to use them with a different
database schema.

The default implementation assumes that the password is stored in the database as a SHA-512 hash after being
concatenated with a salt. It also assumes the salt is stored in the table too.

If you want to override this behaviour you can do so by providing an alternative hash strategy and setting it with
`link:groovydoc/io/vertx/groovy/ext/auth/jdbc/JDBCAuth.html#setHashStrategy(io.vertx.ext.auth.jdbc.JDBCHashStrategy)[setHashStrategy]`.

WARNING: It is advised to always store your passwords as hashes in your database tables which have been created
with a salt which should be stored in the row too. A strong hashing algorithm should be used. It is strongly advised
never to store your passwords as plain text.