= Cheatsheets

[[JDBCAuthenticationOptions]]
== JDBCAuthenticationOptions

++++
 Options configuring JDBC authentication.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[authenticationQuery]]`@authenticationQuery`|`String`|+++
Set the authentication query to use. Use this if you want to override the default authentication query.
+++
|[[config]]`@config`|`Json object`|+++
The configuration of the JDBC client: refer to the Vert.x JDBC Client configuration.
+++
|[[datasourceName]]`@datasourceName`|`String`|+++
Set the data source name to use, only use in shared mode.
+++
|[[shared]]`@shared`|`Boolean`|+++
Set whether the JDBC client is shared or non shared.
+++
|===

[[JDBCAuthorizationOptions]]
== JDBCAuthorizationOptions

++++
 Options configuring JDBC authorization
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[datasourceName]]`@datasourceName`|`String`|+++
Set the data source name to use, only use in shared mode.
+++
|[[permissionsQuery]]`@permissionsQuery`|`String`|+++
Set the permissions query to use. Use this if you want to override the
 default permissions query.
+++
|[[rolesQuery]]`@rolesQuery`|`String`|+++
Set the roles query to use. Use this if you want to override the default
 roles query.
+++
|[[shared]]`@shared`|`Boolean`|+++
Set whether the JDBC client is shared or non shared.
+++
|===

