= Cheatsheets

[[MongoAuthOptions]]
== MongoAuthOptions

++++
 Options configuring Mongo authentication.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[collectionName]]`@collectionName`|`String`|+++
The property name to be used to set the name of the collection inside the config.
+++
|[[config]]`@config`|`Json object`|+++
The mongo client configuration: see Mongo Client documentation.
+++
|[[datasourceName]]`@datasourceName`|`String`|+++
The mongo data source name: see Mongo Client documentation.
+++
|[[passwordField]]`@passwordField`|`String`|+++
The property name to be used to set the name of the field, where the password is stored inside
+++
|[[permissionField]]`@permissionField`|`String`|+++
The property name to be used to set the name of the field, where the permissions are stored inside.
+++
|[[roleField]]`@roleField`|`String`|+++
The property name to be used to set the name of the field, where the roles are stored inside.
+++
|[[saltField]]`@saltField`|`String`|+++
The property name to be used to set the name of the field, where the SALT is stored inside.
+++
|[[saltStyle]]`@saltStyle`|`link:enums.html#HashSaltStyle[HashSaltStyle]`|+++
The property name to be used to set the name of the field, where the salt style is stored inside
+++
|[[shared]]`@shared`|`Boolean`|+++
Use a shared Mongo client or not.
+++
|[[usernameCredentialField]]`@usernameCredentialField`|`String`|+++
The property name to be used to set the name of the field, where the username for the credentials is stored inside.
+++
|[[usernameField]]`@usernameField`|`String`|+++
The property name to be used to set the name of the field, where the username is stored inside.
+++
|===

