= Cheatsheets

[[MongoAuthenticationOptions]]
== MongoAuthenticationOptions

++++
 Options configuring Mongo authentication.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[collectionName]]`@collectionName`|`String`|+++
The property name to be used to set the name of the collection inside the config.
+++
|[[usernameField]]`@usernameField`|`String`|+++
The property name to be used to set the name of the field, where the username is stored inside.
+++
|[[passwordField]]`@passwordField`|`String`|+++
The property name to be used to set the name of the field, where the password is stored inside
+++
|[[usernameCredentialField]]`@usernameCredentialField`|`String`|+++
The property name to be used to set the name of the field, where the username for the credentials is stored inside.
+++
|[[passwordCredentialField]]`@passwordCredentialField`|`String`|+++
The property name to be used to set the name of the field, where the password for the credentials is stored inside.
+++
|

== MongoAuthorizationOptions

++++
 Options configuring Mongo authorization.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[collectionName]]`@collectionName`|`String`|+++
The property name to be used to set the name of the collection inside the config.
+++
|[[passwordField]]`@passwordField`|`String`|+++
The property name to be used to set the name of the field, where the password is stored inside
+++
|[[permissionField]]`@permissionField`|`String`|+++
The property name to be used to set the name of the field, where the permissions are stored inside.
+++
|[[roleField]]`@roleField`|`String`|+++
The property name to be used to set the name of the field, where the roles are stored inside.
+++
|[[usernameCredentialField]]`@usernameCredentialField`|`String`|+++
The property name to be used to set the name of the field, where the username for the credentials is stored inside.
+++
|[[usernameField]]`@usernameField`|`String`|+++
The property name to be used to set the name of the field, where the username is stored inside.
+++
|===

