== JDBC Auth Provider implementation

We provide an implementation of `link:../../vertx-auth-common/js/jsdoc/auth_provider-AuthProvider.html[AuthProvider]` which uses the Vert.x `link:../../vertx-jdbc-client/js/jsdoc/jdbc_client-JDBCClient.html[JDBCClient]`
to perform authentication and authorisation against any JDBC compliant database.

To create an instance you first need an instance of `link:../../vertx-jdbc-client/js/jsdoc/jdbc_client-JDBCClient.html[JDBCClient]`. To learn how to create one
of those please consult the documentation for the JDBC client.

Once you've got one of those you can create a `link:jsdoc/jdbc_auth-JDBCAuth.html[JDBCAuth]` instance as follows:

[source,java]
----
var JDBCClient = require("vertx-jdbc-js/jdbc_client");
var JDBCAuth = require("vertx-auth-jdbc-js/jdbc_auth");

var jdbcClient = JDBCClient.createShared(vertx, jdbcClientConfig);

var authProvider = JDBCAuth.create(jdbcClient);

----

Once you've got your instance you can authenticate and authorise with it just like any `link:../../vertx-auth-common/js/jsdoc/auth_provider-AuthProvider.html[AuthProvider]`.

The out of the box config assumes certain queries for authentication and authorisation, these can easily be changed
with the operations `link:jsdoc/jdbc_auth-JDBCAuth.html#setAuthenticationQuery[setAuthenticationQuery]`,
`link:jsdoc/jdbc_auth-JDBCAuth.html#setPermissionsQuery[setPermissionsQuery]` and
`link:jsdoc/jdbc_auth-JDBCAuth.html#setRolesQuery[setRolesQuery]`, if you want to use them with a different
database schema.

The default implementation assumes that the password is stored in the database as a SHA-512 hash after being
concatenated with a salt. It also assumes the salt is stored in the table too.

If you want to override this behaviour you can do so by providing an alternative hash strategy and setting it with
`link:jsdoc/jdbc_auth-JDBCAuth.html#setHashStrategy[setHashStrategy]`.

WARNING: It is advised to always store your passwords as hashes in your database tables which have been created
with a salt which should be stored in the row too. A strong hashing algorithm should be used. It is strongly advised
never to store your passwords as plain text.

== Authentication

When authenticating using this implementation, it assumes `username` and `password` fields are present in the
authentication info:

[source,java]
----

var authInfo = {
  "username" : "tim",
  "password" : "sausages"
};

authProvider.authenticate(authInfo, function (res, res_err) {
  if (res_err == null) {
    var user = res;
  } else {
    // Failed!
  };
});

----

== Authorisation - Permission-Role Model

Although Vert.x auth itself does not mandate any specific model of permissions (they are just opaque strings), this
implementation assumes a familiar user/role/permission model, where a user can have zero or more roles and a role
can have zero or more permissions.

If validating if a user has a particular permission simply pass the permission into.
`link:../../vertx-auth-common/js/jsdoc/user-User.html#isPermitted[isPermitted]` as follows:

[source,java]
----

user.isPermitted("commit_code", function (res, res_err) {
  if (res_err == null) {
    var hasPermission = res;
  } else {
    // Failed to
  };
});


----

If validating that a user has a particular _role_ then you should prefix the argument with the role prefix.

[source,java]
----

user.isPermitted("role:manager", function (res, res_err) {
  if (res_err == null) {
    var hasRole = res;
  } else {
    // Failed to
  };
});


----

The default role prefix is `role:`. You can change this with `link:jsdoc/jdbc_auth-JDBCAuth.html#setRolePrefix[setRolePrefix]`.