= Vert.x Auth - Authentication and Authorisation

This Vert.x component provides interfaces for authentication and authorisation that can be used from your Vert.x
applications and can be backed by different providers.

It also provides an implementation that uses http://shiro.apache.org/[Apache Shiro] out-of-the-box but you can provide
your own implementation by implementing the `link:jsdoc/auth_provider-AuthProvider.html[AuthProvider]` interface.

The Vert.x Apache Shiro implementation
currently allows user/role/permission information to be accessed from simple properties files or LDAP servers.

Vert.x auth is also used by vertx-web to handle its authentication and authorisation.

== Basic concepts

_Authentication_ (aka _log in_) means verifying the identity of a user.

_Authorisation_ means verifying a user is allowed to access some resource.

The service uses a familiar user/role/permission model that you will probably know already:

Users can have zero or more roles, e.g. "manager", "developer".

Roles can have zero or more permissions, e.g. a manager might have permission "approve expenses", "conduct_reviews",
and a developer might have a permission "commit_code".

== Authentication

To authenticate a user you use `link:jsdoc/auth_provider-AuthProvider.html#authenticate[authenticate]`.

The first argument is a JSON object which contains authentication information. What this actually contains depends
on the specific implementation; for a simple username/password based authentication it might contain something like:

----
{
  "username": "tim"
  "password": "mypassword"
}
----

For an implementation based on JWT token or OAuth bearer tokens it might contain the token information.

Authentication occurs asynchronously and the result is passed to the user on the result handler that was provided in
the call. The async result contains an instance of `link:jsdoc/user-User.html[User]` which represents the authenticated
user and contains operations which allow the user to be authorised.

Here's an example of authenticating a user using a simple username/password implementation:

[source,java]
----

var authInfo = {
  "username" : "tim",
  "password" : "mypassword"
};

authProvider.authenticate(authInfo, function (res, res_err) {
  if (res_err == null) {

    var user = res;

    console.log("User " + user.principal() + " is now authenticated");

  } else {
    res_err.printStackTrace();
  };
});

----

== Authorisation

Once you have an `link:jsdoc/user-User.html[User]` instance you can call methods on it to authorise it.

To check if a user has a specific role you use `link:jsdoc/user-User.html#hasRole[hasRole]`,
to check if a user has all the specified roles you use `link:jsdoc/user-User.html#hasRoles[hasRoles]`,
to check if a user has a specific permission you use `link:jsdoc/user-User.html#hasPermission[hasPermission]`,
to check if a user has all the specified permissions you use `link:jsdoc/user-User.html#hasPermissions[hasPermissions]`.

The results of all the above are provided asynchronously in the handler.

Here's an example of authorising a user:

[source,java]
----

user.hasPermission("admin", function (res, res_err) {
  if (res_err == null) {

    var hasPermission = res;

    if (hasPermission) {
      console.log("User has the permision");
    } else {
      console.log("User does not have the permision");
    };

  } else {
    res_err.printStackTrace();
  };
});

----

=== Caching roles and permissions

The user object will cache any roles and permissions so subsequently calls to check if it has the same roles or
permissions will result in the underlying provider being called.

In order to clear the internal cache you can use `link:jsdoc/user-User.html#clearCache[clearCache]`.

=== The User Principal

You can get the Principal corresponding to the authenticated user with `link:jsdoc/user-User.html#principal[principal]`.

What this returns depends on the underlying implementation.

== Creating your own auth implementation

If you wish to create your own auth provider you should implement the `link:jsdoc/auth_provider-AuthProvider.html[AuthProvider]` interface.

We provide an abstract implementation of user called `AbstractUser` which you can subclass
to make your user implementation. This contains the caching logic so you don't have to implement that yourself.

If you wish your user objects to be clusterable you should make sure they implement `ClusterSerializable`.